# Generated by Django 4.2.30 on 2026-06-04 22:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='add_on_names',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='add_on_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.CreateModel(
            name='MenuItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='cafe.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='menuitemaddon',
            constraint=models.UniqueConstraint(fields=('menu_item', 'name'), name='unique_menu_item_add_on'),
        ),
    ]
