# Generated by Django 4.2.30 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_orderitem_add_on_names_orderitem_add_on_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[('counter', 'Pay at counter'), ('stripe', 'Stripe card')],
                default='counter',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[('due', 'Due at collection'), ('pending', 'Card payment pending'), ('paid', 'Paid')],
                default='due',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
